### ISSUE TITLE
Expanded description formatting

### ISSUE THREAD

**Issue by duarte** [guardian/docs-interactive-template#10]
Possible regression in the container with the film synopsis:
- the text box is too tight with the date/social media column
- the credits section (which needs slightly different formatting) is missing?

<img width="1168" alt="screen shot 2016-08-24 at 12 07 27" src="https://cloud.githubusercontent.com/assets/4561/17928593/5d372cd6-69f3-11e6-9d38-51de23f7b008.png">

**Comment by mr-mr** [comment]
Latest PR I just did address part of this, checkout master and see if you're happy
