### ISSUE TITLE
Clicking inside the 'About these films' box shouldn't close the box

### ISSUE THREAD

**Issue by duarte** [guardian/docs-interactive-template#34]
Clicking the (X) or the background overlay should close the box, but selecting text should not

<img width="1334" alt="screen shot 2016-09-05 at 10 40 03" src="https://cloud.githubusercontent.com/assets/4561/18243863/26326d98-7355-11e6-8688-d204ee6206a8.png">

**Comment by mr-mr** [comment]
Resolved with PR: https://github.com/guardian/docs-interactive-template/pull/41
