### ISSUE TITLE
Next doc person is overlapping the copy

### ISSUE THREAD

**Issue by mr-mr** [guardian/docs-interactive-template#43]
![image](https://cloud.githubusercontent.com/assets/2067172/18273316/86e80eb0-7434-11e6-838f-2af1904d5da0.png)

**Comment by mr-mr** [comment]
@duarte

**Comment by duarte** [comment]
hey @mr-mr thanks for flagging this up — I will do some edits on this area today!

**Comment by duarte** [comment]
Fixed by PR #51
