### ISSUE TITLE
items blocking launch

### ISSUE THREAD

**Issue by akash1810** [guardian/docs-interactive-template#48]
- [x] full publication date on page (legal)
- [x] plumbing for social elements - perform an e2e test
- [x] setup vanity urls (gu.com/documentaries => tag page, gu.com/documentaries/gun-nation => interactive page)
- [x] replace videos with the real ones
- [x] in article elements
- [x] get full sign off from Editorial

**Comment by gidsg** [comment]
Who asked for the vanity URL, is it needed for the newspaper? I would rather kick back on it otherwise.

**Comment by akash1810** [comment]
@gidsg Editorial asked for marketing purposes. We can use https://frontend.gutools.co.uk/redirects to do this.

**Comment by duarte** [comment]
Re: full publication date
Charlie checked with legal in August and we didn't need it: "Legal are OK with us just having month and year on site as long as we can track exact date and time of release behind the scenes, which we can So this is all fine"

**Comment by duarte** [comment]
BTW there's a typo above the redirects list above "documentries" _> documentaries, just noting to make sure that doesnt get accidentally copied and pasted in the actual redirect! :)

**Comment by gidsg** [comment]
If we put a redirect from `gu.com/documentaries` to the doc we are blocking future use of this URL. I am not a huge fan of this. I would rather do like `gu.com/gun-nation` or `gu.com/bertha` or something.

**Comment by gidsg** [comment]
@duarte I think this is fine as the publication date and modification date are available in the page source for audit purposes.

**Comment by akash1810** [comment]
>  I would rather do like gu.com/gun-nation or gu.com/bertha or something.

Makes sense. Run it past Charlie - he just wants a short url that's easy to remember...
