### ISSUE TITLE
Large screen issues

### ISSUE THREAD

**Issue by duarte** [guardian/docs-interactive-template#57]
Just noticed a a couple of bugs with the page on larger screens: the video does not take up the full width, and the page does not take up the full height — attaching screenshots for reference…

![screen shot 2016-09-08 at 22 31 14](https://cloud.githubusercontent.com/assets/4561/18367790/b47ba026-7614-11e6-9cad-769347da2c05.png)
![screen shot 2016-09-08 at 22 31 06](https://cloud.githubusercontent.com/assets/4561/18367791/b47fa928-7614-11e6-941e-1873afa3b61a.png)

**Comment by mr-mr** [comment]
I can take look, be a nice break from video JS
