### ISSUE TITLE
"Coming soon" text alignment on mobile

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/docs-interactive-template#82]
The text alignment with the coming soon section of the template seems very odd on mobile.
It only extends halfway across the width of the screen and is inconsistent with the sections above and below it.

![image](https://cloud.githubusercontent.com/assets/7239344/19243248/ba524a96-8f0e-11e6-9d14-4775e0db4fd3.png)

**Comment by akash1810** [comment]
an image is missing from this section - we'll add it as soon as its available.

**Comment by akash1810** [comment]
Fixed wth new design of this element. Closing.
