### ISSUE TITLE
Coming soon - Incorrect title

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/docs-interactive-template#83]
Desert fire is the name of the current story.
I think the heading has been probagated to the Coming soon section by mistake.
Looking at the preview, I'm guessing the correct heading should be:
"On the road: sex work in Italy" - or something along those lines.

![image](https://cloud.githubusercontent.com/assets/7239344/19243405/77ebedd2-8f0f-11e6-8fc9-0939eb93627d.png)

**Comment by akash1810** [comment]
Fixed here - https://github.com/guardian/docs-interactive-template/pull/73 but currently blocked on design and editorial.

**Comment by akash1810** [comment]
Fixed wth new design of this element. Closing.
