### ISSUE TITLE
403 - forbidden error on video play

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/docs-interactive-template#85]
Testing on iPad air - when I try to play the video, I get the following error:
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://assets-secure.guim.co.uk/javascripts/ad93420bf0d984bd22a0862fb80fb083/boot.js.map

The video still seems to play though.

**Comment by gidsg** [comment]
This will only happen if the console is open, as it's related to sourcemaps, so won't fix.
