### ISSUE TITLE
iPad air - takes two presses of play to actually play the video

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/docs-interactive-template#86]
On an iPad Air running Safari, I press play here:
![image](https://cloud.githubusercontent.com/assets/7239344/19244081/96468f46-8f12-11e6-959f-e7ded969b444.png)

Video starts to play but hangs with message "if playback doesn't begin shortly, try restarting your device":
![image](https://cloud.githubusercontent.com/assets/7239344/19244104/aacd1c5a-8f12-11e6-9c7d-3e3736e81ff2.png)

At any time pressing play a second time on this page, commences video play.

**Comment by gidsg** [comment]
This is a known issue in iOS <= 9 not allowing autoplay we are not going to fix it for this project.
